### ISSUE TITLE
My file size is correct?

### ISSUE THREAD

**Issue by aylalab** [aylalab/but-em-buttons#1]
<img width="794" alt="Screen Shot 2019-10-09 at 9 17 20 PM" src="https://user-images.githubusercontent.com/43240315/66531600-59b03100-eada-11e9-82b7-668e8d370a4d.png">
<img width="236" alt="Screen Shot 2019-10-09 at 9 17 16 PM" src="https://user-images.githubusercontent.com/43240315/66531602-59b03100-eada-11e9-85cc-a96c2275713f.png">

Markbot is telling me my svg is too big when it's the proper size. Please help!
@charlie-quinn
@thomasjbradley

**Comment by charlie-quinn** [comment]
- [ ] resize artwork in AI to be 100px in height
  - this asset is pretty small on our site, so we don't need it to be any larger than this
- [ ] smush it using `spritebot` and/or [svgomg](https://jakearchibald.github.io/svgomg/)
Markbot should be much happier 🤖🎉

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
